name: Python Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Playwright browsers and dependencies
      - name: Install Playwright browsers
        run: |
          python -m playwright install
          python -m playwright install-deps

      # Add project root to PYTHONPATH
      - name: Add PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      # Run pytest
      - name: Run tests with pytest
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0 # Ensure Playwright uses locally installed browsers
        run: pytest tests/ --cache-clear --maxfail=5 --tb=short
