name: Python Playwright Tests

on:
  push:
    branches:
      - main    # Trigger for pushes to the main branch (you can modify the branch as needed)
  pull_request:
    branches:
      - main    # Trigger for pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest    # Use the latest Ubuntu runner
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Matrix of Python versions to test against

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Playwright dependencies
      - name: Install Playwright
        run: |
          python -m playwright install

      # Run tests with pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Optionally upload test results or coverage reports if necessary
      # - name: Upload test results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: pytest-results
      #     path: result.xml   # specify the path to your test result file, if you use pytest --junitxml=result.xml
